### ISSUE TITLE
add() is slow

### ISSUE THREAD

**Issue by odbol** [atljeremy/PriorityQueue-ObjC#1]
Hey, thanks for making this, it's very helpful. I noticed a bug in add() though: it goes through the trouble of doing a binary search for a fast insert, which is great, but then it throws all that optimization away by calling `contains()` directly afterwards (which is most likely a linear search at O(n)). 

I fixed it like this:

```
- (void)add:(id<NSObject>)object
{
    [self insertObjectUsingBinarySearch:object];
}
```

**Comment by atljeremy** [comment]
@odbol Good call. Can you open a PR with this update?

**Comment by atljeremy** [comment]
Addressed in https://github.com/atljeremy/PriorityQueue-ObjC/commit/0cec23d243535c42966158635b0ed3fb4c358341
